# Generated by Django 4.2.7 on 2024-04-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "пользователь"), ("admin", "админ")],
                default="user",
                max_length=150,
                verbose_name="роль пользователя",
            ),
        ),
    ]
