# Generated by Django 4.2.7 on 2024-04-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "админ"), ("user", "пользователь")],
                default="user",
                max_length=150,
                verbose_name="роль пользователя",
            ),
        ),
    ]
