# Generated by Django 4.2.7 on 2024-04-06 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_alter_ad_options_alter_review_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="title",
            field=models.CharField(max_length=200, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 22, 6, 35, 401655),
                verbose_name="дата публиувции отзыва",
            ),
        ),
    ]
