# Generated by Django 4.2.7 on 2024-04-09 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_alter_ad_title_alter_review_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 9, 17, 40, 27, 418189),
                verbose_name="дата публиувции отзыва",
            ),
        ),
    ]
