# Generated by Django 4.2.7 on 2024-04-11 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0004_alter_review_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 11, 6, 36, 37, 525287),
                verbose_name="дата публиувции отзыва",
            ),
        ),
    ]
