# Generated by Django 4.2.7 on 2024-04-13 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0006_alter_ad_author_alter_ad_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор отзыва",
            ),
        ),
    ]
